name: Workflow

on:
  push:
    branches: [develop, main] 
  pull_request:
    branches: [develop, main] 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
       node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run compile
      env:
          PRIVATE_KEY: 123456789abcdef123456789abcdef123456789abcdef123456789abcdef1234
    - run: npm run tests:lint
    - run: npm run contracts:lint
    - run: npm run contracts:format
    - run: npm run test
      env:
          PRIVATE_KEY: 123456789abcdef123456789abcdef123456789abcdef123456789abcdef1234


